name: Duels
author: Dartanman
main: xyz.minefalls.duels.Main
version: 3.0.7
api-version: 1.16
commands:
  dueladmin:
    description: Duels base command
    usage: /<command>
  duel:
    description: Duel someone!
    usage: /<command> PlayerName