name: MineFallsDuels
author: TheGiorno
main: xyz.minefalls.duels.Main
version: 1.0
api-version: 1.16
commands:
  dueladmin:
    description: Duels admin commands
    usage: /<command>
  duel:
    description: Duel someone!
    usage: /<command> PlayerName